version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: teste_ans_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ans_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d/
volumes:
  postgres_data: